name: Playwright Tests - Dev

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        tag-group:
          - name: 'playwright-dev'
            tags: '@playwright-dev'

    uses: ./.github/workflows/playwright-template.yml
    with:
      test-name: ${{ matrix.tag-group.name }}
      test-tags: ${{ matrix.tag-group.tags }}
    secrets: inherit 